# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(401, 300)
        Dialog.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 401, 151))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color:rgb(255, 0, 0)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_drag = QtWidgets.QPushButton(self.frame)
        self.btn_drag.setGeometry(QtCore.QRect(160, 60, 75, 23))
        self.btn_drag.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.btn_drag.setObjectName("btn_drag")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 180, 61, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.btn_open_window = QtWidgets.QPushButton(Dialog)
        self.btn_open_window.setGeometry(QtCore.QRect(260, 230, 75, 23))
        self.btn_open_window.setObjectName("btn_open_window")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 210, 147, 22))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 0, 1, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 0, 2, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(10, 260, 161, 16))
        self.checkBox.setObjectName("checkBox")
        self.frame.raise_()
        self.gridLayoutWidget.raise_()
        self.pushButton_2.raise_()
        self.btn_open_window.raise_()
        self.checkBox.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_drag.setText(_translate("Dialog", "Drag"))
        self.pushButton_2.setText(_translate("Dialog", "+"))
        self.btn_open_window.setText(_translate("Dialog", "Open Window"))
        self.radioButton_2.setText(_translate("Dialog", "2"))
        self.radioButton_3.setText(_translate("Dialog", "3"))
        self.radioButton.setText(_translate("Dialog", "1"))
        self.checkBox.setText(_translate("Dialog", "Show Only Selected"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
